// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  adminStatsApiAdminStatsGet,
  chatApiChatPost,
  createFeedbackApiFeedbackPost,
  createUsageLogApiUsageLogsPost,
  healthCheckHealthGet,
  type Options,
  searchFaqApiFaqSearchGet,
} from "../sdk.gen";
import type {
  AdminStatsApiAdminStatsGetData,
  AdminStatsApiAdminStatsGetResponse,
  ChatApiChatPostData,
  ChatApiChatPostError,
  ChatApiChatPostResponse,
  CreateFeedbackApiFeedbackPostData,
  CreateFeedbackApiFeedbackPostError,
  CreateFeedbackApiFeedbackPostResponse,
  CreateUsageLogApiUsageLogsPostData,
  CreateUsageLogApiUsageLogsPostError,
  CreateUsageLogApiUsageLogsPostResponse,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponse,
  SearchFaqApiFaqSearchGetData,
  SearchFaqApiFaqSearchGetError,
  SearchFaqApiFaqSearchGetResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthCheckHealthGetQueryKey = (
  options?: Options<HealthCheckHealthGetData>,
) => createQueryKey("healthCheckHealthGet", options);

/**
 * Health Check
 *
 * サービスの死活監視エンドポイント。
 */
export const healthCheckHealthGetOptions = (
  options?: Options<HealthCheckHealthGetData>,
) =>
  queryOptions<
    HealthCheckHealthGetResponse,
    DefaultError,
    HealthCheckHealthGetResponse,
    ReturnType<typeof healthCheckHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthCheckHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthCheckHealthGetQueryKey(options),
  });

/**
 * Chat
 *
 * Dify Chat API を呼び出してLLMの回答を返すエンドポイント。
 */
export const chatApiChatPostMutation = (
  options?: Partial<Options<ChatApiChatPostData>>,
): UseMutationOptions<
  ChatApiChatPostResponse,
  ChatApiChatPostError,
  Options<ChatApiChatPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ChatApiChatPostResponse,
    ChatApiChatPostError,
    Options<ChatApiChatPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await chatApiChatPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const searchFaqApiFaqSearchGetQueryKey = (
  options: Options<SearchFaqApiFaqSearchGetData>,
) => createQueryKey("searchFaqApiFaqSearchGet", options);

/**
 * Search Faq
 *
 * FAQをキーワードで検索するエンドポイント(P0: LIKE検索)。
 */
export const searchFaqApiFaqSearchGetOptions = (
  options: Options<SearchFaqApiFaqSearchGetData>,
) =>
  queryOptions<
    SearchFaqApiFaqSearchGetResponse,
    SearchFaqApiFaqSearchGetError,
    SearchFaqApiFaqSearchGetResponse,
    ReturnType<typeof searchFaqApiFaqSearchGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchFaqApiFaqSearchGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchFaqApiFaqSearchGetQueryKey(options),
  });

/**
 * Create Feedback
 *
 * チャット回答への👍/👎フィードバックを保存するエンドポイント。
 */
export const createFeedbackApiFeedbackPostMutation = (
  options?: Partial<Options<CreateFeedbackApiFeedbackPostData>>,
): UseMutationOptions<
  CreateFeedbackApiFeedbackPostResponse,
  CreateFeedbackApiFeedbackPostError,
  Options<CreateFeedbackApiFeedbackPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateFeedbackApiFeedbackPostResponse,
    CreateFeedbackApiFeedbackPostError,
    Options<CreateFeedbackApiFeedbackPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createFeedbackApiFeedbackPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Usage Log
 *
 * チャットAPIから呼ばれるトークン消費ログ保存エンドポイント。
 */
export const createUsageLogApiUsageLogsPostMutation = (
  options?: Partial<Options<CreateUsageLogApiUsageLogsPostData>>,
): UseMutationOptions<
  CreateUsageLogApiUsageLogsPostResponse,
  CreateUsageLogApiUsageLogsPostError,
  Options<CreateUsageLogApiUsageLogsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUsageLogApiUsageLogsPostResponse,
    CreateUsageLogApiUsageLogsPostError,
    Options<CreateUsageLogApiUsageLogsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUsageLogApiUsageLogsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminStatsApiAdminStatsGetQueryKey = (
  options?: Options<AdminStatsApiAdminStatsGetData>,
) => createQueryKey("adminStatsApiAdminStatsGet", options);

/**
 * Admin Stats
 *
 * 管理ダッシュボード用KPI集計エンドポイント。
 */
export const adminStatsApiAdminStatsGetOptions = (
  options?: Options<AdminStatsApiAdminStatsGetData>,
) =>
  queryOptions<
    AdminStatsApiAdminStatsGetResponse,
    DefaultError,
    AdminStatsApiAdminStatsGetResponse,
    ReturnType<typeof adminStatsApiAdminStatsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminStatsApiAdminStatsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminStatsApiAdminStatsGetQueryKey(options),
  });
