// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  adminStatsApiAdminStatsGet,
  callbackApiAuthCallbackGet,
  chatApiChatPost,
  createFeedbackApiFeedbackPost,
  createUsageLogUsageLogsPost,
  feedbackListApiAdminFeedbacksGet,
  healthCheckHealthGet,
  loginApiAuthLoginGet,
  logoutApiAuthLogoutPost,
  meApiAuthMeGet,
  type Options,
  searchFaqApiFaqSearchGet,
} from "../sdk.gen";
import type {
  AdminStatsApiAdminStatsGetData,
  AdminStatsApiAdminStatsGetResponse,
  CallbackApiAuthCallbackGetData,
  CallbackApiAuthCallbackGetError,
  ChatApiChatPostData,
  ChatApiChatPostError,
  ChatApiChatPostResponse,
  CreateFeedbackApiFeedbackPostData,
  CreateFeedbackApiFeedbackPostError,
  CreateFeedbackApiFeedbackPostResponse,
  CreateUsageLogUsageLogsPostData,
  CreateUsageLogUsageLogsPostError,
  CreateUsageLogUsageLogsPostResponse,
  FeedbackListApiAdminFeedbacksGetData,
  FeedbackListApiAdminFeedbacksGetError,
  FeedbackListApiAdminFeedbacksGetResponse,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponse,
  LoginApiAuthLoginGetData,
  LogoutApiAuthLogoutPostData,
  MeApiAuthMeGetData,
  MeApiAuthMeGetResponse,
  SearchFaqApiFaqSearchGetData,
  SearchFaqApiFaqSearchGetError,
  SearchFaqApiFaqSearchGetResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthCheckHealthGetQueryKey = (
  options?: Options<HealthCheckHealthGetData>,
) => createQueryKey("healthCheckHealthGet", options);

/**
 * Health Check
 *
 * サービスの死活監視エンドポイント。
 */
export const healthCheckHealthGetOptions = (
  options?: Options<HealthCheckHealthGetData>,
) =>
  queryOptions<
    HealthCheckHealthGetResponse,
    DefaultError,
    HealthCheckHealthGetResponse,
    ReturnType<typeof healthCheckHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthCheckHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthCheckHealthGetQueryKey(options),
  });

export const loginApiAuthLoginGetQueryKey = (
  options?: Options<LoginApiAuthLoginGetData>,
) => createQueryKey("loginApiAuthLoginGet", options);

/**
 * Login
 *
 * Discord OAuth 認可画面にリダイレクトする。
 */
export const loginApiAuthLoginGetOptions = (
  options?: Options<LoginApiAuthLoginGetData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof loginApiAuthLoginGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await loginApiAuthLoginGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: loginApiAuthLoginGetQueryKey(options),
  });

export const callbackApiAuthCallbackGetQueryKey = (
  options: Options<CallbackApiAuthCallbackGetData>,
) => createQueryKey("callbackApiAuthCallbackGet", options);

/**
 * Callback
 *
 * Discord OAuth コールバック。トークンを交換してセッション Cookie を発行する。
 */
export const callbackApiAuthCallbackGetOptions = (
  options: Options<CallbackApiAuthCallbackGetData>,
) =>
  queryOptions<
    unknown,
    CallbackApiAuthCallbackGetError,
    unknown,
    ReturnType<typeof callbackApiAuthCallbackGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await callbackApiAuthCallbackGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: callbackApiAuthCallbackGetQueryKey(options),
  });

export const meApiAuthMeGetQueryKey = (options?: Options<MeApiAuthMeGetData>) =>
  createQueryKey("meApiAuthMeGet", options);

/**
 * Me
 *
 * 現在ログイン中のユーザー情報を返す。
 */
export const meApiAuthMeGetOptions = (options?: Options<MeApiAuthMeGetData>) =>
  queryOptions<
    MeApiAuthMeGetResponse,
    DefaultError,
    MeApiAuthMeGetResponse,
    ReturnType<typeof meApiAuthMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await meApiAuthMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: meApiAuthMeGetQueryKey(options),
  });

/**
 * Logout
 *
 * Cookie を削除してログアウトする。
 */
export const logoutApiAuthLogoutPostMutation = (
  options?: Partial<Options<LogoutApiAuthLogoutPostData>>,
): UseMutationOptions<
  unknown,
  DefaultError,
  Options<LogoutApiAuthLogoutPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<LogoutApiAuthLogoutPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logoutApiAuthLogoutPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Chat
 *
 * Dify Chat API を呼び出してLLMの回答を返すエンドポイント。
 */
export const chatApiChatPostMutation = (
  options?: Partial<Options<ChatApiChatPostData>>,
): UseMutationOptions<
  ChatApiChatPostResponse,
  ChatApiChatPostError,
  Options<ChatApiChatPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ChatApiChatPostResponse,
    ChatApiChatPostError,
    Options<ChatApiChatPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await chatApiChatPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const searchFaqApiFaqSearchGetQueryKey = (
  options: Options<SearchFaqApiFaqSearchGetData>,
) => createQueryKey("searchFaqApiFaqSearchGet", options);

/**
 * Search Faq
 *
 * FAQをキーワードで検索するエンドポイント(P0: LIKE検索)。
 */
export const searchFaqApiFaqSearchGetOptions = (
  options: Options<SearchFaqApiFaqSearchGetData>,
) =>
  queryOptions<
    SearchFaqApiFaqSearchGetResponse,
    SearchFaqApiFaqSearchGetError,
    SearchFaqApiFaqSearchGetResponse,
    ReturnType<typeof searchFaqApiFaqSearchGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchFaqApiFaqSearchGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchFaqApiFaqSearchGetQueryKey(options),
  });

/**
 * Create Feedback
 *
 * チャット回答への👍/👎フィードバックを保存するエンドポイント。
 */
export const createFeedbackApiFeedbackPostMutation = (
  options?: Partial<Options<CreateFeedbackApiFeedbackPostData>>,
): UseMutationOptions<
  CreateFeedbackApiFeedbackPostResponse,
  CreateFeedbackApiFeedbackPostError,
  Options<CreateFeedbackApiFeedbackPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateFeedbackApiFeedbackPostResponse,
    CreateFeedbackApiFeedbackPostError,
    Options<CreateFeedbackApiFeedbackPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createFeedbackApiFeedbackPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Usage Log
 *
 * チャットAPIから呼ばれるトークン消費ログ保存エンドポイント。
 */
export const createUsageLogUsageLogsPostMutation = (
  options?: Partial<Options<CreateUsageLogUsageLogsPostData>>,
): UseMutationOptions<
  CreateUsageLogUsageLogsPostResponse,
  CreateUsageLogUsageLogsPostError,
  Options<CreateUsageLogUsageLogsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUsageLogUsageLogsPostResponse,
    CreateUsageLogUsageLogsPostError,
    Options<CreateUsageLogUsageLogsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUsageLogUsageLogsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const adminStatsApiAdminStatsGetQueryKey = (
  options?: Options<AdminStatsApiAdminStatsGetData>,
) => createQueryKey("adminStatsApiAdminStatsGet", options);

/**
 * Admin Stats
 *
 * 管理ダッシュボード用KPI集計エンドポイント。
 */
export const adminStatsApiAdminStatsGetOptions = (
  options?: Options<AdminStatsApiAdminStatsGetData>,
) =>
  queryOptions<
    AdminStatsApiAdminStatsGetResponse,
    DefaultError,
    AdminStatsApiAdminStatsGetResponse,
    ReturnType<typeof adminStatsApiAdminStatsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await adminStatsApiAdminStatsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: adminStatsApiAdminStatsGetQueryKey(options),
  });

export const feedbackListApiAdminFeedbacksGetQueryKey = (
  options?: Options<FeedbackListApiAdminFeedbacksGetData>,
) => createQueryKey("feedbackListApiAdminFeedbacksGet", options);

/**
 * Feedback List
 *
 * フィードバック一覧を返す。
 */
export const feedbackListApiAdminFeedbacksGetOptions = (
  options?: Options<FeedbackListApiAdminFeedbacksGetData>,
) =>
  queryOptions<
    FeedbackListApiAdminFeedbacksGetResponse,
    FeedbackListApiAdminFeedbacksGetError,
    FeedbackListApiAdminFeedbacksGetResponse,
    ReturnType<typeof feedbackListApiAdminFeedbacksGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await feedbackListApiAdminFeedbacksGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: feedbackListApiAdminFeedbacksGetQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const feedbackListApiAdminFeedbacksGetInfiniteQueryKey = (
  options?: Options<FeedbackListApiAdminFeedbacksGetData>,
): QueryKey<Options<FeedbackListApiAdminFeedbacksGetData>> =>
  createQueryKey("feedbackListApiAdminFeedbacksGet", options, true);

/**
 * Feedback List
 *
 * フィードバック一覧を返す。
 */
export const feedbackListApiAdminFeedbacksGetInfiniteOptions = (
  options?: Options<FeedbackListApiAdminFeedbacksGetData>,
) =>
  infiniteQueryOptions<
    FeedbackListApiAdminFeedbacksGetResponse,
    FeedbackListApiAdminFeedbacksGetError,
    InfiniteData<FeedbackListApiAdminFeedbacksGetResponse>,
    QueryKey<Options<FeedbackListApiAdminFeedbacksGetData>>,
    | number
    | Pick<
        QueryKey<Options<FeedbackListApiAdminFeedbacksGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<FeedbackListApiAdminFeedbacksGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await feedbackListApiAdminFeedbacksGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: feedbackListApiAdminFeedbacksGetInfiniteQueryKey(options),
    },
  );
