// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AdminStatsApiAdminStatsGetData,
  AdminStatsApiAdminStatsGetResponses,
  CallbackApiAuthCallbackGetData,
  CallbackApiAuthCallbackGetErrors,
  CallbackApiAuthCallbackGetResponses,
  ChatApiChatPostData,
  ChatApiChatPostErrors,
  ChatApiChatPostResponses,
  CreateFeedbackApiFeedbackPostData,
  CreateFeedbackApiFeedbackPostErrors,
  CreateFeedbackApiFeedbackPostResponses,
  CreateUsageLogUsageLogsPostData,
  CreateUsageLogUsageLogsPostErrors,
  CreateUsageLogUsageLogsPostResponses,
  FeedbackListApiAdminFeedbacksGetData,
  FeedbackListApiAdminFeedbacksGetErrors,
  FeedbackListApiAdminFeedbacksGetResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
  LoginApiAuthLoginGetData,
  LoginApiAuthLoginGetResponses,
  LogoutApiAuthLogoutPostData,
  LogoutApiAuthLogoutPostResponses,
  MeApiAuthMeGetData,
  MeApiAuthMeGetResponses,
  SearchFaqApiFaqSearchGetData,
  SearchFaqApiFaqSearchGetErrors,
  SearchFaqApiFaqSearchGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * サービスの死活監視エンドポイント。
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthCheckHealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/health", ...options });

/**
 * Login
 *
 * Discord OAuth 認可画面にリダイレクトする。
 */
export const loginApiAuthLoginGet = <ThrowOnError extends boolean = false>(
  options?: Options<LoginApiAuthLoginGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    LoginApiAuthLoginGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/auth/login", ...options });

/**
 * Callback
 *
 * Discord OAuth コールバック。トークンを交換してセッション Cookie を発行する。
 */
export const callbackApiAuthCallbackGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CallbackApiAuthCallbackGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CallbackApiAuthCallbackGetResponses,
    CallbackApiAuthCallbackGetErrors,
    ThrowOnError
  >({ url: "/api/auth/callback", ...options });

/**
 * Me
 *
 * 現在ログイン中のユーザー情報を返す。
 */
export const meApiAuthMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<MeApiAuthMeGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    MeApiAuthMeGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/auth/me", ...options });

/**
 * Logout
 *
 * Cookie を削除してログアウトする。
 */
export const logoutApiAuthLogoutPost = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutApiAuthLogoutPostData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    LogoutApiAuthLogoutPostResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/auth/logout", ...options });

/**
 * Chat
 *
 * Dify Chat API を呼び出してLLMの回答を返すエンドポイント。
 */
export const chatApiChatPost = <ThrowOnError extends boolean = false>(
  options: Options<ChatApiChatPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ChatApiChatPostResponses,
    ChatApiChatPostErrors,
    ThrowOnError
  >({
    url: "/api/chat",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search Faq
 *
 * FAQをキーワードで検索するエンドポイント(P0: LIKE検索)。
 */
export const searchFaqApiFaqSearchGet = <ThrowOnError extends boolean = false>(
  options: Options<SearchFaqApiFaqSearchGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchFaqApiFaqSearchGetResponses,
    SearchFaqApiFaqSearchGetErrors,
    ThrowOnError
  >({ url: "/api/faq/search", ...options });

/**
 * Create Feedback
 *
 * チャット回答への👍/👎フィードバックを保存するエンドポイント。
 */
export const createFeedbackApiFeedbackPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateFeedbackApiFeedbackPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateFeedbackApiFeedbackPostResponses,
    CreateFeedbackApiFeedbackPostErrors,
    ThrowOnError
  >({
    url: "/api/feedback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Usage Log
 *
 * チャットAPIから呼ばれるトークン消費ログ保存エンドポイント。
 */
export const createUsageLogUsageLogsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateUsageLogUsageLogsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateUsageLogUsageLogsPostResponses,
    CreateUsageLogUsageLogsPostErrors,
    ThrowOnError
  >({
    url: "/usage-logs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Admin Stats
 *
 * 管理ダッシュボード用KPI集計エンドポイント。
 */
export const adminStatsApiAdminStatsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminStatsApiAdminStatsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AdminStatsApiAdminStatsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/stats", ...options });

/**
 * Feedback List
 *
 * フィードバック一覧を返す。
 */
export const feedbackListApiAdminFeedbacksGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<FeedbackListApiAdminFeedbacksGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    FeedbackListApiAdminFeedbacksGetResponses,
    FeedbackListApiAdminFeedbacksGetErrors,
    ThrowOnError
  >({ url: "/api/admin/feedbacks", ...options });
