// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AdminStatsApiAdminStatsGetData,
  AdminStatsApiAdminStatsGetResponses,
  ChatApiChatPostData,
  ChatApiChatPostErrors,
  ChatApiChatPostResponses,
  CreateFeedbackApiFeedbackPostData,
  CreateFeedbackApiFeedbackPostErrors,
  CreateFeedbackApiFeedbackPostResponses,
  CreateUsageLogApiUsageLogsPostData,
  CreateUsageLogApiUsageLogsPostErrors,
  CreateUsageLogApiUsageLogsPostResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
  SearchFaqApiFaqSearchGetData,
  SearchFaqApiFaqSearchGetErrors,
  SearchFaqApiFaqSearchGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * サービスの死活監視エンドポイント。
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthCheckHealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/health", ...options });

/**
 * Chat
 *
 * Dify Chat API を呼び出してLLMの回答を返すエンドポイント。
 */
export const chatApiChatPost = <ThrowOnError extends boolean = false>(
  options: Options<ChatApiChatPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ChatApiChatPostResponses,
    ChatApiChatPostErrors,
    ThrowOnError
  >({
    url: "/api/chat",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search Faq
 *
 * FAQをキーワードで検索するエンドポイント(P0: LIKE検索)。
 */
export const searchFaqApiFaqSearchGet = <ThrowOnError extends boolean = false>(
  options: Options<SearchFaqApiFaqSearchGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchFaqApiFaqSearchGetResponses,
    SearchFaqApiFaqSearchGetErrors,
    ThrowOnError
  >({ url: "/api/faq/search", ...options });

/**
 * Create Feedback
 *
 * チャット回答への👍/👎フィードバックを保存するエンドポイント。
 */
export const createFeedbackApiFeedbackPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateFeedbackApiFeedbackPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateFeedbackApiFeedbackPostResponses,
    CreateFeedbackApiFeedbackPostErrors,
    ThrowOnError
  >({
    url: "/api/feedback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Usage Log
 *
 * チャットAPIから呼ばれるトークン消費ログ保存エンドポイント。
 */
export const createUsageLogApiUsageLogsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateUsageLogApiUsageLogsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateUsageLogApiUsageLogsPostResponses,
    CreateUsageLogApiUsageLogsPostErrors,
    ThrowOnError
  >({
    url: "/api/usage-logs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Admin Stats
 *
 * 管理ダッシュボード用KPI集計エンドポイント。
 */
export const adminStatsApiAdminStatsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AdminStatsApiAdminStatsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AdminStatsApiAdminStatsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/admin/stats", ...options });
