// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * ChatRequest
 *
 * チャットリクエスト。
 */
export const zChatRequest = z.object({
  session_id: z.string().min(1).max(128),
  message: z.string().min(1).max(5000),
});

/**
 * ChatResponse
 *
 * チャットレスポンス。
 */
export const zChatResponse = z.object({
  answer: z.string(),
  tokens_used: z.int(),
});

/**
 * DailyCount
 */
export const zDailyCount = z.object({
  day: z.iso.date(),
  count: z.int(),
});

/**
 * AdminStatsResponse
 */
export const zAdminStatsResponse = z.object({
  daily_questions: z.array(zDailyCount),
  total_tokens: z.int(),
});

/**
 * FaqSearchResult
 *
 * FAQ検索結果の1件。
 */
export const zFaqSearchResult = z.object({
  content: z.string(),
});

/**
 * FaqSearchResponse
 *
 * FAQ検索レスポンス。
 */
export const zFaqSearchResponse = z.object({
  results: z.array(zFaqSearchResult),
});

/**
 * FeedbackCreate
 *
 * フィードバック作成リクエスト。
 */
export const zFeedbackCreate = z.object({
  session_id: z.string().min(1).max(128),
  rating: z.enum(["good", "bad"]),
  comment: z.string().max(500).nullish(),
});

/**
 * FeedbackResponse
 *
 * フィードバックレスポンス。
 */
export const zFeedbackResponse = z.object({
  id: z.string(),
  session_id: z.string(),
  rating: z.string(),
  comment: z.string().nullable(),
  created_at: z.iso.datetime(),
});

/**
 * HealthResponse
 */
export const zHealthResponse = z.object({
  status: z.string(),
  db: z.string(),
});

/**
 * UsageLogCreate
 *
 * トークン消費ログ作成リクエスト。
 */
export const zUsageLogCreate = z.object({
  session_id: z.string().min(1),
  tokens: z.int().gte(1),
  category: z.string().nullish(),
});

/**
 * UsageLogResponse
 *
 * トークン消費ログレスポンス。
 */
export const zUsageLogResponse = z.object({
  id: z.string(),
  session_id: z.string(),
  tokens: z.int(),
  category: z.string().nullable(),
  created_at: z.iso.datetime(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
  input: z.unknown().optional(),
  ctx: z.record(z.string(), z.unknown()).optional(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

export const zHealthCheckHealthGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zHealthCheckHealthGetResponse = zHealthResponse;

export const zChatApiChatPostData = z.object({
  body: zChatRequest,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zChatApiChatPostResponse = zChatResponse;

export const zSearchFaqApiFaqSearchGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.object({
    q: z.string().min(1).max(200),
  }),
});

/**
 * Successful Response
 */
export const zSearchFaqApiFaqSearchGetResponse = zFaqSearchResponse;

export const zCreateFeedbackFeedbackPostData = z.object({
  body: zFeedbackCreate,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zCreateFeedbackFeedbackPostResponse = zFeedbackResponse;

export const zCreateUsageLogUsageLogsPostData = z.object({
  body: zUsageLogCreate,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zCreateUsageLogUsageLogsPostResponse = zUsageLogResponse;

export const zGetAdminStatsApiAdminStatsGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zGetAdminStatsApiAdminStatsGetResponse = zAdminStatsResponse;
