// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  ChatApiChatPostData,
  ChatApiChatPostErrors,
  ChatApiChatPostResponses,
  CreateUsageLogUsageLogsPostData,
  CreateUsageLogUsageLogsPostErrors,
  CreateUsageLogUsageLogsPostResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * サービスの死活監視エンドポイント。
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
    url: "/health",
    ...options,
  });

/**
 * Chat
 *
 * Dify Chat API を呼び出してLLMの回答を返すエンドポイント。
 */
export const chatApiChatPost = <ThrowOnError extends boolean = false>(
  options: Options<ChatApiChatPostData, ThrowOnError>
) =>
  (options.client ?? client).post<ChatApiChatPostResponses, ChatApiChatPostErrors, ThrowOnError>({
    url: "/api/chat",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Usage Log
 *
 * チャットAPIから呼ばれるトークン消費ログ保存エンドポイント。
 */
export const createUsageLogUsageLogsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateUsageLogUsageLogsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUsageLogUsageLogsPostResponses,
    CreateUsageLogUsageLogsPostErrors,
    ThrowOnError
  >({
    url: "/usage-logs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
