// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AdminStatsResponse
 */
export type AdminStatsResponse = {
  /**
   * Daily Questions
   */
  daily_questions: Array<DailyCount>;
  /**
   * Total Tokens
   */
  total_tokens: number;
};

/**
 * ChatRequest
 *
 * チャットリクエスト。
 */
export type ChatRequest = {
  /**
   * Session Id
   */
  session_id: string;
  /**
   * Message
   */
  message: string;
};

/**
 * ChatResponse
 *
 * チャットレスポンス。
 */
export type ChatResponse = {
  /**
   * Answer
   */
  answer: string;
  /**
   * Tokens Used
   */
  tokens_used: number;
};

/**
 * DailyCount
 */
export type DailyCount = {
  /**
   * Day
   */
  day: string;
  /**
   * Count
   */
  count: number;
};

/**
 * FaqSearchResponse
 *
 * FAQ検索レスポンス。
 */
export type FaqSearchResponse = {
  /**
   * Results
   */
  results: Array<FaqSearchResult>;
};

/**
 * FaqSearchResult
 *
 * FAQ検索結果の1件。
 */
export type FaqSearchResult = {
  /**
   * Content
   */
  content: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
  /**
   * Status
   */
  status: string;
  /**
   * Db
   */
  db: string;
};

/**
 * UsageLogCreate
 *
 * トークン消費ログ作成リクエスト。
 */
export type UsageLogCreate = {
  /**
   * Session Id
   */
  session_id: string;
  /**
   * Tokens
   */
  tokens: number;
  /**
   * Category
   */
  category?: string | null;
};

/**
 * UsageLogResponse
 *
 * トークン消費ログレスポンス。
 */
export type UsageLogResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Session Id
   */
  session_id: string;
  /**
   * Tokens
   */
  tokens: number;
  /**
   * Category
   */
  category: string | null;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: HealthResponse;
};

export type HealthCheckHealthGetResponse =
  HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type ChatApiChatPostData = {
  body: ChatRequest;
  path?: never;
  query?: never;
  url: "/api/chat";
};

export type ChatApiChatPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ChatApiChatPostError = ChatApiChatPostErrors[keyof ChatApiChatPostErrors];

export type ChatApiChatPostResponses = {
  /**
   * Successful Response
   */
  200: ChatResponse;
};

export type ChatApiChatPostResponse = ChatApiChatPostResponses[keyof ChatApiChatPostResponses];

export type SearchFaqApiFaqSearchGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Q
     *
     * 検索キーワード
     */
    q: string;
  };
  url: "/api/faq/search";
};

export type SearchFaqApiFaqSearchGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchFaqApiFaqSearchGetError =
  SearchFaqApiFaqSearchGetErrors[keyof SearchFaqApiFaqSearchGetErrors];

export type SearchFaqApiFaqSearchGetResponses = {
  /**
   * Successful Response
   */
  200: FaqSearchResponse;
};

export type SearchFaqApiFaqSearchGetResponse =
  SearchFaqApiFaqSearchGetResponses[keyof SearchFaqApiFaqSearchGetResponses];

export type CreateUsageLogUsageLogsPostData = {
  body: UsageLogCreate;
  path?: never;
  query?: never;
  url: "/usage-logs";
};

export type CreateUsageLogUsageLogsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUsageLogUsageLogsPostError =
  CreateUsageLogUsageLogsPostErrors[keyof CreateUsageLogUsageLogsPostErrors];

export type CreateUsageLogUsageLogsPostResponses = {
  /**
   * Successful Response
   */
  201: UsageLogResponse;
};

export type CreateUsageLogUsageLogsPostResponse =
  CreateUsageLogUsageLogsPostResponses[keyof CreateUsageLogUsageLogsPostResponses];

export type GetAdminStatsApiAdminStatsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/admin/stats";
};

export type GetAdminStatsApiAdminStatsGetResponses = {
  /**
   * Successful Response
   */
  200: AdminStatsResponse;
};

export type GetAdminStatsApiAdminStatsGetResponse =
  GetAdminStatsApiAdminStatsGetResponses[keyof GetAdminStatsApiAdminStatsGetResponses];
