// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * HealthResponse
 */
export const zHealthResponse = z.object({
  status: z.string(),
  db: z.string(),
});

export const zHealthCheckHealthGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zHealthCheckHealthGetResponse = zHealthResponse;
